language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install click click-didyoumean
# command to run tests
script:
  - pytest